version: 2.1

jobs:
  print_hello:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - command: |
          echo "Hello world"
          ls
          pwd
  print_world:
    docker:
      - image: alpine:latest
    steps:
      - run: echo world

workflows:
  welcome:
    jobs:
      - print_hello
      - print_world